title: "Becoming a Cyborg"
description: "Chronicles of a CTO merging with his AI"
author: Daniel Albertini
url: "https://cyborgd.com"
baseurl: ""

remote_theme: b2a3e8/jekyll-theme-console
style: hacker

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

tracking: true

header_pages:
  - index.md
  - about.md
