title: "Becoming a Cyborg"
description: "Chronicles of a CTO merging with his AI"
author: Daniel Albertini
url: "https://danielalbertini.github.io"
baseurl: "/cto-agent-blog"

remote_theme: b2a3e8/jekyll-theme-console
style: hacker

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md
